name: Builds

on:
  push:

jobs:
  build_job:
    runs-on: [windows-2022]

    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      run: msbuild AOC2021.sln -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: MSTest
      shell: powershell
      working-directory: bin\Release\net6.0
      run: '& "$(vswhere -property installationPath)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" Solutions.dll'